export { BackgroundQuantizer } from './quantizer';
export type { QuantizerConfig } from './quantizer';
export { ValueRangeAllocator } from './value-range';
export type { ValueRangeConfig, NeuronAllocation } from './value-range';
export { MoERouter } from './moe-router';
export type { MoEConfig, RouterDecision, MoELayerOutput, ExpertUtilizationStats } from './moe-router';
export { ExpertNetwork } from './expert';
export type { ExpertConfig, ExpertMetadata } from './expert';
export { NeuronMesh } from './mesh';
export type { NeuronNode, MeshTopology, PropagationResult, MeshConfig } from './mesh';
export { HyperDimensionalEngine } from './hyperdimensional';
export type { HyperNeuron, StateTransition, HyperDimensionalOutput, HyperConfig, SeenPattern } from './hyperdimensional';
export { RLMTrainer } from './rlm';
export type { RLMConfig, Experience, ThinkStep, ReplayBuffer, TrainingResult, PolicyState } from './rlm';
export { ThornsEngine, CodeToNet } from './thorns';
export type { QuestionDimension, ThornNode, QuestionNode, IntentResult, CrossCheckResult, SimulateResult, ThornsOutput, CodeNeuron, CodeNetTopology } from './thorns';
export { NeuroLangInterpreter } from './neuro-lang';
export type { ParseResult } from './neuro-lang';
export { NeuroPipeline } from './pipeline';
export type { PipelineConfig, PipelineStep, PipelineResult } from './pipeline';
export { QuantumNeuralNet, quantumNet } from './quantum-net';
export type { QuantumState, QuantumNeuron } from './quantum-net';
export { InfiniteZipLoop, ZipIOSystem } from './zip-io';
export type { ZipChunk } from './zip-io';

export { ElasticCoreBlock } from './elastic-core';
export type { ElasticCoreConfig, ElasticCoreRunOptions, ElasticCoreResult } from './elastic-core';
