interface ModelData {
    id: string;
    name: string;
    version: string;
    format: string;
    weights: Record<string, number[]>;
    metadata?: Record<string, any>;
}
declare class ModelFileLoader {
    loadModel(filePath: string): ModelData;
    getModelInfo(model: ModelData): Record<string, any>;
    listModels(directory: string): string[];
    validateModel(data: any): data is ModelData;
}
export { ModelFileLoader };
export type { ModelData as LegacyModelData } from "./index.js";
export { NeuroclawLLM } from "./llm.js";
export type { LLMConfig, GenerateOptions } from "./llm.js";
export { SkillsManager } from "./skills-manager.js";
export type { SkillActivation, SkillUsageStats, SkillsManagerConfig } from "./skills-manager.js";
export { PROGRAMMING_SKILLS, getSkillById, getSkillsByCategory, getSkillsByExpertType, searchSkills, getAllCategories, getAllExpertTypes } from "./programming-skills.js";
export type { ProgrammingSkill } from "./programming-skills.js";
export { ModelManager } from "./model-manager.js";
export type { ModelMetadata, ModelData, ModelLoadOptions, ModelSaveOptions, ModelManagerConfig } from "./model-manager.js";
export { PluginManager } from "./plugin-manager.js";
export type { PluginMetadata, PluginInstance, PluginManagerConfig } from "./plugin-manager.js";
export { MixtureOfExperts } from "./core/onebrain.js";
export type { Expert } from "./core/onebrain.js";
export { NeuroclawTrainer } from "./trainer.js";
export type { TrainingConfig, NGramTable, TrainedWeights } from "./trainer.js";
export { Tokenizer } from "./tokenizer.js";
export { Neuron } from "./neuron.js";
export type { NeuronState } from "./neuron.js";
export { SimulationEngine } from "./simulation.js";
export type { IntentAnalysis, SimulationResult, ReviewOutcome, FinalOutput, WH } from "./simulation.js";
export { BackgroundQuantizer } from "./core/quantizer.js";
export type { QuantizerConfig } from "./core/quantizer.js";
export { ValueRangeAllocator } from "./core/value-range.js";
export type { ValueRangeConfig, NeuronAllocation } from "./core/value-range.js";
export { MoERouter } from "./core/onebrain.js";
export type { MoEConfig, RouterDecision, MoELayerOutput, ExpertUtilizationStats } from "./core/onebrain.js";
export { NeuronMesh } from "./core/onebrain.js";
export type { NeuronNode, MeshTopology, PropagationResult, MeshConfig } from "./core/onebrain.js";
export { HyperDimensionalEngine } from "./core/onebrain.js";
export type { HyperNeuron, StateTransition, HyperDimensionalOutput, HyperConfig, SeenPattern } from "./core/onebrain.js";
export { RLMTrainer } from "./core/rlm.js";
export type { RLMConfig, Experience, ThinkStep, ReplayBuffer, TrainingResult, PolicyState } from "./core/rlm.js";
export { NeuroLangInterpreter } from "./core/neuro-lang.js";
export type { NeuriNeuron, ParseResult } from "./core/neuro-lang.js";
export { NeuroPipeline } from "./core/pipeline.js";
export type { PipelineConfig, PipelineStep, PipelineResult } from "./core/pipeline.js";
export { ExpertNetwork } from "./core/expert.js";
export type { ExpertConfig, ExpertMetadata } from "./core/expert.js";
