import type { PluginDefinition, ExtensionManifest, SkillDefinition } from "../plugin_manager/types";
import type { BasePlugin } from "../plugin_manager/sdk";
export { LocationPlugin } from "./location";
export { CameraPlugin } from "./camera";
export { MicrophonePlugin } from "./microphone";
export { VoiceActivationPlugin } from "./voice-activation";
export { NotificationsPlugin } from "./notifications";
export { AccountInfoPlugin } from "./account-info";
export { ContactsPlugin } from "./contacts";
export { CalendarPlugin } from "./calendar";
export { PhoneCallsPlugin } from "./phone-calls";
export { CallHistoryPlugin } from "./call-history";
export { EmailPlugin } from "./email";
export { TasksPlugin } from "./tasks";
export { MessagingPlugin } from "./messaging";
export { RadiosPlugin } from "./radios";
export { OtherDevicesPlugin } from "./other-devices";
export { AppDiagnosticsPlugin } from "./app-diagnostics";
export { ScreenshotsPlugin } from "./screenshots";
export { BrowserPlugin } from "./browser";
export { FileSystemPlugin } from "./file-system";
export { PasskeysPlugin } from "./passkeys";
export { MultiInputPlugin } from "./multi-input";
export { CodingExtension } from "./extensions/coding";
export { ImageExtension, VideoExtension, GameExtension, SelfHealExtension, SkillMakerExtension, PluginMakerExtension } from "./extensions";
export declare function createPluginInstance(name: string, definition: PluginDefinition, skillDefinition?: SkillDefinition): BasePlugin;
declare const pluginExtensions: Record<string, PluginDefinition>;
declare const allExtensions: ExtensionManifest[];
export { pluginExtensions, allExtensions as ALL_EXTENSIONS };
