/**
 * Linux permission tools.
 *
 * Every permission capability has a distinct callable tool descriptor. Tools
 * are deny-by-default: they require a current permission grant, Linux runtime,
 * and a registered native adapter. High-impact actions also require per-call
 * human approval. Adapters must use fixed executable allowlists / native APIs;
 * never pass model-authored strings to a shell.
 *
 * A capability is not a privilege escalation. Unix DAC, ACLs, polkit, sudo,
 * capabilities, namespaces, SELinux, AppArmor and administrator policy remain
 * authoritative. Lennox tools require a separately configured official
 * integration and intentionally fail closed when it is absent.
 */

import type { ExtensionPermission } from "../plugin_manager/types.js";

export interface LinuxToolCallContext {
  /** Must verify a grant for this exact capability and requesting extension. */
  isGranted: (extensionId: string, permission: ExtensionPermission) => boolean;
  /** Ask the human for this specific operation; return false on denial/timeout. */
  requestApproval: (request: { tool: string; permission: ExtensionPermission; args: Record<string, unknown>; risk: "high" | "critical" }) => Promise<boolean>;
  /** A native, validated adapter registered by the host for this capability. */
  adapters: Partial<Record<ExtensionPermission, (args: Record<string, unknown>) => Promise<unknown>>>;
  /** Defaults to process.platform; injectable for tests. */
  platform?: NodeJS.Platform;
}

export interface LinuxPermissionTool {
  name: string;
  permission: ExtensionPermission;
  category: string;
  description: string;
  risk: "high" | "critical";
  inputSchema: {
    type: "object";
    properties: Record<string, { type: string; description: string; enum?: string[]; minimum?: number; maximum?: number }>;
    required: string[];
    additionalProperties: false;
  };
  execute: (args: Record<string, unknown>, context: LinuxToolCallContext, extensionId?: string) => Promise<unknown>;
}

type ToolSpec = {
  permission: ExtensionPermission;
  category: string;
  description: string;
  risk?: "high" | "critical";
  properties?: Record<string, { type: string; description: string; enum?: string[]; minimum?: number; maximum?: number }>;
  required?: string[];
};

const commonPath = { path: { type: "string", description: "Absolute or app-authorized filesystem path." } };
const action = { action: { type: "string", description: "Explicit operation requested from the supported adapter." } };
const target = { target: { type: "string", description: "Target identifier, path, unit, device, or resource name." } };
const specs: ToolSpec[] = [
  { permission: "linux-file-read", category: "Filesystem", description: "Read a file or a bounded file range.", properties: { ...commonPath, offset: { type: "number", description: "Byte offset.", minimum: 0 }, limit: { type: "number", description: "Maximum bytes to return.", minimum: 1, maximum: 1048576 } }, required: ["path"] },
  { permission: "linux-file-write", category: "Filesystem", description: "Write or replace a file; adapter must validate path and content size.", properties: { ...commonPath, content: { type: "string", description: "Text content to write." }, mode: { type: "number", description: "Optional octal mode, e.g. 384 for 0600.", minimum: 0, maximum: 511 } }, required: ["path", "content"] },
  { permission: "linux-file-execute", category: "Filesystem", description: "Execute an explicitly approved executable by absolute path with an argument array.", properties: { path: { type: "string", description: "Absolute executable path; no shell." }, args: { type: "array", description: "Argument list passed without shell expansion." } }, required: ["path", "args"] },
  { permission: "linux-file-create-delete", category: "Filesystem", description: "Create, move, or delete a filesystem entry.", properties: { ...action, path: commonPath.path, destination: { type: "string", description: "Destination path for a move." } }, required: ["action", "path"] },
  { permission: "linux-file-metadata", category: "Filesystem", description: "Read file type, ownership, mode, size, and timestamps.", properties: commonPath, required: ["path"] },
  { permission: "linux-chmod", category: "Unix permissions", description: "Change Unix permission bits using a numeric mode.", properties: { ...commonPath, mode: { type: "number", description: "Octal mode expressed as an integer, e.g. 493 for 0755.", minimum: 0, maximum: 4095 } }, required: ["path", "mode"] },
  { permission: "linux-chown", category: "Unix permissions", description: "Change file owner/group by numeric UID/GID.", properties: { ...commonPath, uid: { type: "number", description: "Numeric user ID.", minimum: 0 }, gid: { type: "number", description: "Numeric group ID.", minimum: 0 } }, required: ["path"] },
  { permission: "linux-suid-sgid-sticky", category: "Unix permissions", description: "Inspect or change SUID, SGID, and sticky bits.", properties: { ...commonPath, mode: { type: "number", description: "Full numeric mode including special bits.", minimum: 0, maximum: 4095 } }, required: ["path"] },
  { permission: "linux-acl-read", category: "ACL", description: "Read POSIX access/default ACL entries.", properties: commonPath, required: ["path"] },
  { permission: "linux-acl-write", category: "ACL", description: "Set or remove explicit POSIX ACL entries.", properties: { ...commonPath, entries: { type: "array", description: "Validated ACL entry list; adapter must reject malformed entries." } }, required: ["path", "entries"] },
  { permission: "linux-extended-attributes", category: "Filesystem security", description: "List, read, set, or remove extended attributes.", properties: { ...commonPath, name: { type: "string", description: "Attribute name." }, value: { type: "string", description: "Attribute value." }, action: { type: "string", description: "list, get, set, or remove.", enum: ["list", "get", "set", "remove"] } }, required: ["path", "action"] },
  { permission: "linux-immutable-append-only", category: "Filesystem security", description: "Inspect or change immutable/append-only filesystem flags.", properties: { ...commonPath, flags: { type: "array", description: "Requested flags: immutable or append-only." }, action: { type: "string", description: "inspect, set, or clear.", enum: ["inspect", "set", "clear"] } }, required: ["path", "action"] },
  { permission: "linux-mount-unmount", category: "Storage", description: "Inspect mounts or mount/unmount an approved device and target.", properties: { ...target, action: { type: "string", description: "list, mount, or unmount.", enum: ["list", "mount", "unmount"] }, source: { type: "string", description: "Device or source for mount." }, path: { type: "string", description: "Mount point." }, filesystem: { type: "string", description: "Filesystem type." } }, required: ["action"] },
  { permission: "linux-removable-storage", category: "Storage", description: "Enumerate and safely eject removable storage.", properties: { ...target, action: { type: "string", description: "list, inspect, or eject.", enum: ["list", "inspect", "eject"] } }, required: ["action"] },
  { permission: "linux-user-group-read", category: "Accounts", description: "Read local account and group metadata without exposing password hashes.", properties: { ...target, kind: { type: "string", description: "user or group.", enum: ["user", "group"] } }, required: ["kind"] },
  { permission: "linux-user-group-admin", category: "Accounts", description: "Create, modify, or remove local users/groups.", properties: { ...action, ...target, kind: { type: "string", description: "user or group.", enum: ["user", "group"] }, uid: { type: "number", description: "Optional numeric UID/GID.", minimum: 0 }, groups: { type: "array", description: "Explicit supplementary groups." } }, required: ["action", "kind", "target"] },
  { permission: "linux-sudo-admin", category: "Administration", description: "Request a narrowly scoped privileged action through polkit or a host-approved helper; never collect a sudo password.", properties: { ...action, ...target }, required: ["action"] , risk:"critical" },
  { permission: "linux-process-inspect", category: "Processes", description: "List processes and inspect selected process metadata.", properties: { ...target, pid: { type: "number", description: "Process ID.", minimum: 1 } }, required: [] },
  { permission: "linux-process-control", category: "Processes", description: "Send a named signal to a process after validating PID ownership and approval.", properties: { pid: { type: "number", description: "Process ID.", minimum: 1 }, signal: { type: "string", description: "Signal name.", enum: ["SIGTERM", "SIGINT", "SIGHUP", "SIGKILL"] } }, required: ["pid", "signal"], risk:"critical" },
  { permission: "linux-service-control", category: "Services", description: "Inspect/start/stop/restart an allowlisted system service.", properties: { ...target, action: { type: "string", description: "status, start, stop, restart, enable, disable.", enum: ["status", "start", "stop", "restart", "enable", "disable"] } }, required: ["target", "action"], risk:"critical" },
  { permission: "linux-package-management", category: "Packages", description: "Query, install, update, or remove packages through the detected package manager.", properties: { ...target, action: { type: "string", description: "search, info, install, update, remove.", enum: ["search", "info", "install", "update", "remove"] } }, required: ["action"], risk:"critical" },
  { permission: "linux-kernel-modules", category: "Kernel", description: "List or request loading/unloading a named kernel module.", properties: { ...target, action: { type: "string", description: "list, inspect, load, unload.", enum: ["list", "inspect", "load", "unload"] } }, required: ["action"], risk:"critical" },
  { permission: "linux-sysctl", category: "Kernel", description: "Read or change an explicitly named sysctl key.", properties: { ...target, value: { type: "string", description: "New value for the named key." }, action: { type: "string", description: "get or set.", enum: ["get", "set"] } }, required: ["target", "action"] },
  { permission: "linux-hostname-time-power", category: "Host", description: "Read hostname/time or request a hostname/time/power change.", properties: { ...action, value: { type: "string", description: "New hostname or ISO timestamp where applicable." } }, required: ["action"] , risk:"critical" },
  { permission: "linux-boot-configuration", category: "Boot", description: "Inspect boot settings or propose a reviewed boot configuration change.", properties: { ...action, ...target, content: { type: "string", description: "Proposed configuration content." } }, required: ["action"], risk:"critical" },
  { permission: "linux-scheduled-jobs", category: "Scheduling", description: "List or manage this user's scheduled jobs.", properties: { ...action, id: { type: "string", description: "Job identifier." }, schedule: { type: "string", description: "Schedule expression." }, command: { type: "string", description: "Executable and arguments, validated by adapter." } }, required: ["action"], risk:"critical" },
  { permission: "linux-environment-variables", category: "Host", description: "Read or set process-scoped environment variables; system-wide changes require approval.", properties: { name: { type: "string", description: "Variable name." }, value: { type: "string", description: "Variable value." }, action: { type: "string", description: "get, set, list.", enum: ["get", "set", "list"] } }, required: ["action"] },
  { permission: "linux-system-logs", category: "Logs", description: "Read filtered system/service logs with bounded output.", properties: { ...target, since: { type: "string", description: "Time window or ISO timestamp." }, limit: { type: "number", description: "Maximum records.", minimum: 1, maximum: 2000 } }, required: [] },
  { permission: "linux-audit-logs", category: "Logs", description: "Read filtered security audit events; secret fields must be redacted.", properties: { ...target, since: { type: "string", description: "Time window or ISO timestamp." }, limit: { type: "number", description: "Maximum records.", minimum: 1, maximum: 2000 } }, required: [] },
  { permission: "linux-system-information", category: "Host", description: "Read distribution, kernel, architecture, resource, and capability information.", properties: action, required: [] },
  { permission: "linux-backup-restore", category: "Recovery", description: "Create, inspect, verify, or restore a scoped backup.", properties: { ...action, source: { type: "string", description: "Source path or backup ID." }, destination: { type: "string", description: "Backup destination or restore target." } }, required: ["action"], risk:"critical" },
  { permission: "linux-capabilities-admin", category: "Security", description: "Inspect or change Linux file capabilities.", properties: { ...commonPath, action: { type: "string", description: "get, set, remove.", enum: ["get", "set", "remove"] }, capabilities: { type: "string", description: "Capability set expression." } }, required: ["path", "action"], risk:"critical" },
  { permission: "linux-selinux-context-read", category: "SELinux", description: "Read SELinux mode, labels, and policy status.", properties: { ...commonPath, action: { type: "string", description: "status or context.", enum: ["status", "context"] } }, required: ["action"] },
  { permission: "linux-selinux-policy-admin", category: "SELinux", description: "Manage SELinux labels or policy through an installed SELinux adapter.", properties: { ...action, ...commonPath, context: { type: "string", description: "Validated SELinux context." }, policy: { type: "string", description: "Named policy module." } }, required: ["action"], risk:"critical" },
  { permission: "linux-apparmor-status-read", category: "AppArmor", description: "Read AppArmor status and profile enforcement state.", properties: action, required: [] },
  { permission: "linux-apparmor-policy-admin", category: "AppArmor", description: "Manage AppArmor profiles through a validated policy adapter.", properties: { ...action, ...target, content: { type: "string", description: "Proposed profile content." } }, required: ["action"], risk:"critical" },
  { permission: "linux-security-policy-admin", category: "Security", description: "Inspect or change host security policy through an allowlisted policy adapter.", properties: { ...action, ...target }, required: ["action"], risk:"critical" },
  { permission: "linux-firewall-admin", category: "Networking", description: "Inspect or manage firewall rules through nftables/firewalld/ufw adapters.", properties: { ...action, ...target, protocol: { type: "string", description: "tcp or udp.", enum: ["tcp", "udp"] }, port: { type: "number", description: "Port number.", minimum: 1, maximum: 65535 } }, required: ["action"], risk:"critical" },
  { permission: "linux-network-config", category: "Networking", description: "Inspect interfaces/routes or request network configuration changes.", properties: { ...action, ...target, address: { type: "string", description: "IP address or CIDR." } }, required: ["action"], risk:"critical" },
  { permission: "linux-dbus-control", category: "Desktop/system bus", description: "Call an explicitly allowlisted D-Bus service/method.", properties: { service: { type: "string", description: "D-Bus service name." }, path: { type: "string", description: "Object path." }, interface: { type: "string", description: "Interface name." }, method: { type: "string", description: "Allowlisted method name." }, args: { type: "array", description: "Typed D-Bus arguments." } }, required: ["service", "path", "interface", "method"] },
  { permission: "linux-device-access", category: "Devices", description: "Enumerate and inspect authorized hardware devices.", properties: { ...target, action: { type: "string", description: "list or inspect.", enum: ["list", "inspect"] } }, required: ["action"] },
  { permission: "linux-container-control", category: "Containers", description: "Inspect/manage allowlisted containers and images.", properties: { ...target, action: { type: "string", description: "list, inspect, start, stop, restart, logs.", enum: ["list", "inspect", "start", "stop", "restart", "logs"] } }, required: ["action"], risk:"critical" },
  { permission: "linux-namespace-control", category: "Isolation", description: "Inspect or create a constrained namespace/sandbox through a host adapter.", properties: { ...action, ...target }, required: ["action"], risk:"critical" },
  { permission: "linux-credential-store", category: "Secrets", description: "Use the desktop secret service/keyring without returning unrelated secrets.", properties: { ...action, key: { type: "string", description: "Namespaced secret identifier." }, value: { type: "string", description: "Secret value for set operation." } }, required: ["action", "key"], risk:"critical" },
  { permission: "linux-ssh-key-access", category: "Secrets", description: "List public SSH keys or use a named key; private key bytes must not be returned.", properties: { ...action, keyId: { type: "string", description: "Key identifier or public-key path." } }, required: ["action"], risk:"critical" },
  { permission: "linux-certificate-store", category: "Certificates", description: "Inspect or manage system/user certificate trust entries.", properties: { ...action, certificate: { type: "string", description: "Certificate path or fingerprint." } }, required: ["action"], risk:"critical" },
  { permission: "linux-cryptographic-key-access", category: "Secrets", description: "Use a named cryptographic key for an approved operation without exporting key material.", properties: { ...action, keyId: { type: "string", description: "Key identifier." }, data: { type: "string", description: "Data for the requested cryptographic operation." } }, required: ["action", "keyId"], risk:"critical" },
  { permission: "linux-screen-capture", category: "Desktop", description: "Capture the active screen/window using the desktop portal and user consent.", properties: { ...target, mode: { type: "string", description: "screen or window.", enum: ["screen", "window"] } }, required: [] },
  { permission: "linux-audio-device", category: "Desktop", description: "List audio devices or capture/play audio after consent.", properties: { ...action, ...target }, required: ["action"] },
  { permission: "linux-input-monitoring", category: "Desktop", description: "Request supported accessibility/input-monitoring access; do not collect passwords or hidden keystrokes.", properties: action, required: ["action"] , risk:"critical" },
  { permission: "linux-keyboard-mouse-control", category: "Desktop", description: "Perform visible, user-authorized keyboard/mouse actions in the active desktop.", properties: { action: { type: "string", description: "click, move, type, keypress.", enum: ["click", "move", "type", "keypress"] }, x: { type: "number", description: "Screen X coordinate." }, y: { type: "number", description: "Screen Y coordinate." }, text: { type: "string", description: "Text to type visibly." }, key: { type: "string", description: "Named key." } }, required: ["action"], risk:"critical" },
  { permission: "linux-clipboard", category: "Desktop", description: "Read or write the current clipboard.", properties: { action: { type: "string", description: "read or write.", enum: ["read", "write"] }, text: { type: "string", description: "Text to place on clipboard." } }, required: ["action"] },
  { permission: "linux-display-settings", category: "Desktop", description: "Read or change display resolution, scale, and monitor layout.", properties: { ...action, ...target }, required: ["action"] },
  { permission: "linux-printer-access", category: "Peripherals", description: "List printers and inspect/submit/cancel a print job.", properties: { ...action, ...target, file: { type: "string", description: "File to print." } }, required: ["action"] },
  { permission: "linux-bluetooth", category: "Peripherals", description: "Inspect or connect/disconnect a Bluetooth device.", properties: { ...action, ...target }, required: ["action"] },
  { permission: "linux-wifi", category: "Networking", description: "Inspect or connect/disconnect a saved Wi-Fi network without exposing credentials.", properties: { ...action, ...target }, required: ["action"] },
  { permission: "lennox-admin-controls", category: "Lennox business integration", description: "Use approved Lennox administrator controls. Requires a configured official integration.", properties: { ...action, ...target }, required: ["action"], risk:"critical" },
  { permission: "lennox-ordering", category: "Lennox business integration", description: "Create or inspect Lennox orders through a configured official integration.", properties: { ...action, ...target, items: { type: "array", description: "Requested order line items." } }, required: ["action"], risk:"critical" },
  { permission: "lennox-inventory", category: "Lennox business integration", description: "Read or update Lennox inventory through a configured official integration.", properties: { ...action, ...target, quantity: { type: "number", description: "Inventory quantity." } }, required: ["action"], risk:"high" },
  { permission: "lennox-pricing-visibility", category: "Lennox business integration", description: "Read authorized Lennox pricing data through a configured official integration.", properties: target, required: ["target"], risk:"high" },
  { permission: "lennox-warranty-returns", category: "Lennox business integration", description: "Inspect or initiate warranty/return workflows through a configured official integration.", properties: { ...action, ...target, orderId: { type: "string", description: "Order identifier." }, reason: { type: "string", description: "Return/warranty reason." } }, required: ["action"], risk:"critical" },
];

const extendedLinuxSpecs: ToolSpec[] = [
  { permission: "linux-umask", category: "Unix permissions", description: "Read or set process umask with explicit scope.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-default-acl", category: "ACL", description: "Inspect or manage inherited default ACLs.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-quota", category: "Storage", description: "Inspect or change user, group, and project filesystem quotas.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-project-id", category: "Storage", description: "Inspect or set filesystem project IDs and inheritance.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-snapshot", category: "Recovery", description: "Create, list, verify, and remove supported filesystem snapshots.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-repair", category: "Storage", description: "Check filesystem health and request offline repair.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-encryption", category: "Storage security", description: "Inspect or manage supported filesystem encryption policies.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-disk-encryption", category: "Storage security", description: "Inspect encrypted block devices and request approved unlock or lifecycle operations.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-logical-volume-management", category: "Storage", description: "Inspect or manage allowlisted logical volumes, volume groups, and physical volumes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-software-raid", category: "Storage", description: "Inspect or manage software RAID arrays.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-swap-management", category: "Storage", description: "Inspect or manage swap devices and files.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-export", category: "File sharing", description: "Inspect or manage NFS/Samba export configuration.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-fuse-mounts", category: "Storage", description: "Inspect or manage user-space filesystem mounts.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-file-locks", category: "Filesystem", description: "Inspect advisory file locks and lock ownership.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-filesystem-watchers", category: "Filesystem", description: "Manage scoped filesystem watch subscriptions.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-process-priority", category: "Processes", description: "Inspect or change process priority and niceness.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-process-scheduler", category: "Processes", description: "Inspect or change process scheduling policy and real-time priority.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-process-resource-limits", category: "Processes", description: "Inspect or change rlimits and per-service resource limits.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-process-trace", category: "Processes", description: "Request explicitly approved process tracing or debugging access.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-cgroup-control", category: "Isolation", description: "Inspect or change constrained cgroup resource controls.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-seccomp-policy", category: "Isolation", description: "Inspect or apply seccomp profiles to an approved process or sandbox.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-landlock-policy", category: "Isolation", description: "Inspect or apply Landlock filesystem restrictions to a sandbox.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-bpf-control", category: "Kernel security", description: "Inspect approved eBPF programs/maps or request a restricted load.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-perf-events", category: "Kernel diagnostics", description: "Request scoped performance counters and profiling data.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-polkit-policy", category: "Authorization", description: "Inspect authorization rules or request a narrowly scoped polkit action.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-pam-configuration", category: "Authentication", description: "Inspect or propose PAM authentication configuration changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-sudo-policy", category: "Authorization", description: "Inspect sudo policy metadata or propose a reviewed policy change; never read passwords.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-login-session-control", category: "Accounts", description: "Inspect or terminate an explicitly selected login session.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-user-session-control", category: "Desktop", description: "Inspect or manage the current user's desktop session.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-authentication-status", category: "Authentication", description: "Inspect authentication-provider status without exposing password hashes.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-account-lock-status", category: "Accounts", description: "Inspect account lock/expiry status or request an approved account lock.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-ssh-configuration", category: "Remote access", description: "Inspect or propose changes to SSH client/server configuration.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-ssh-agent", category: "Remote access", description: "Use a named SSH agent identity without exporting private keys.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-gpg-keyring", category: "Secrets", description: "Use a named GPG key for approved operations without exporting secret key material.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-keyring-management", category: "Secrets", description: "Inspect or manage the current user's secret-service keyring.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-trust-store", category: "Certificates", description: "Inspect or manage user/system certificate trust anchors.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-secure-boot-status", category: "Boot security", description: "Read Secure Boot, kernel lockdown, and boot-integrity status.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-tpm-access", category: "Hardware security", description: "Request scoped TPM operations without exposing raw secrets.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-firmware-management", category: "Hardware", description: "Inspect firmware versions and request signed firmware updates.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-udev-rules", category: "Devices", description: "Inspect or propose reviewed udev device-policy rules.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-device-node-permissions", category: "Devices", description: "Inspect or modify device-node ownership and access modes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-usb-access", category: "Devices", description: "Enumerate and interact with authorized USB devices.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-serial-port-access", category: "Devices", description: "Access an explicitly selected serial port.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-gpu-access", category: "Devices", description: "Inspect authorized GPU devices and compute sessions.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-hardware-sensors", category: "Hardware", description: "Read exposed temperature, fan, battery, and hardware sensor data.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-power-management", category: "Host", description: "Inspect or change power profiles, sleep, suspend, and hibernate.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-thermal-control", category: "Hardware", description: "Inspect thermal state and request bounded cooling controls.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-time-sync", category: "Host", description: "Inspect or configure NTP/time synchronization.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-locale-settings", category: "Host", description: "Inspect or change locale, timezone, and regional settings.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-dns-configuration", category: "Networking", description: "Inspect or change DNS resolver configuration.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-vpn-control", category: "Networking", description: "Inspect or connect/disconnect a configured VPN profile.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-network-manager", category: "Networking", description: "Inspect or manage allowlisted NetworkManager connections.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-packet-capture", category: "Networking", description: "Capture bounded network traffic only on explicitly approved interfaces.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-traffic-control", category: "Networking", description: "Inspect or change traffic shaping and queueing rules.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-proxy-settings", category: "Networking", description: "Inspect or change system/user proxy settings.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-hosts-file", category: "Networking", description: "Read or propose reviewed edits to the hosts file.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-network-sharing", category: "Networking", description: "Inspect or manage hotspot, forwarding, and connection sharing.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-mdns-discovery", category: "Networking", description: "Discover services announced on the local network.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-network-filesystems", category: "File sharing", description: "Inspect or mount approved NFS, SMB/CIFS, and SSHFS resources.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-dbus-policy", category: "Desktop/system bus", description: "Inspect or propose D-Bus access policy changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-desktop-portals", category: "Desktop", description: "Request user-mediated file, screen, camera, or device access via desktop portals.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-notification-control", category: "Desktop", description: "Read notification capability status or send user-visible notifications.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-screen-lock-control", category: "Desktop security", description: "Inspect screen-lock state or request a lock; never silently unlock.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-accessibility-control", category: "Desktop", description: "Use explicitly granted accessibility APIs for visible UI assistance.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-speech-recognition", category: "Desktop", description: "Request speech recognition using a user-visible microphone consent flow.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-camera-device", category: "Desktop", description: "Access an authorized camera via system APIs and visible consent.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-scanner-access", category: "Peripherals", description: "Enumerate scanners and submit an approved scan job.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-print-queue-admin", category: "Peripherals", description: "Inspect, pause, resume, or cancel print queues and jobs.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-flatpak-permissions", category: "Application sandboxing", description: "Inspect or change Flatpak app permissions/overrides.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-snap-permissions", category: "Application sandboxing", description: "Inspect snap interfaces/connections and request supported changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-app-permission-inventory", category: "Application sandboxing", description: "Inventory desktop application sandbox permissions and grants.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-package-repository-admin", category: "Packages", description: "Inspect or manage signed package repositories and trust configuration.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-automatic-updates", category: "Packages", description: "Inspect or configure automatic security/system updates.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-kernel-log-access", category: "Logs", description: "Read bounded kernel logs with sensitive-field redaction.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-journal-management", category: "Logs", description: "Query journal metadata or request approved journal retention changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-audit-policy", category: "Auditing", description: "Inspect or propose Linux audit rules and policy changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-integrity-monitoring", category: "Security", description: "Inspect file-integrity monitoring, IMA, and EVM status.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-yama-policy", category: "Security", description: "Inspect Yama ptrace restrictions and related kernel policy.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-smack-policy", category: "Security", description: "Inspect SMACK labels or request approved policy changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-tomoyo-policy", category: "Security", description: "Inspect TOMOYO profiles or request approved policy changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-lsm-inventory", category: "Security", description: "Discover enabled Linux Security Modules and their enforcement status.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-kernel-lockdown", category: "Kernel security", description: "Inspect kernel lockdown state; policy changes require explicit approval.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-module-signature-policy", category: "Kernel security", description: "Inspect kernel module signature enforcement.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-iommu-status", category: "Hardware security", description: "Inspect IOMMU status and device isolation.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-virtualization-control", category: "Virtualization", description: "Inspect or manage allowlisted virtual machines and hypervisor resources.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-libvirt-control", category: "Virtualization", description: "Inspect or manage allowlisted libvirt domains and networks.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-systemd-unit-files", category: "Services", description: "Inspect or propose reviewed systemd unit-file changes.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-systemd-timers", category: "Scheduling", description: "Inspect or manage systemd timers.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-user-crontab", category: "Scheduling", description: "Inspect or manage the current user's crontab.", risk: "critical", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-service-permission-inventory", category: "Services", description: "Inventory service identities, unit privileges, and exposed controls.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-policykit-inventory", category: "Authorization", description: "Inventory polkit actions and applicable authorization policy.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-permission-inventory", category: "Permission discovery", description: "Discover available permission mechanisms, installed security frameworks, and current effective grants.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-permission-control-discovery", category: "Permission discovery", description: "Report supported permission controls and which adapters are installed/configured.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
  { permission: "linux-effective-access-check", category: "Permission discovery", description: "Check effective access for a specific user, path, operation, and security context.", properties: { action: { type: "string", description: "Explicit supported operation." }, target: { type: "string", description: "Named resource or identifier." }, path: { type: "string", description: "Resource path where applicable." }, value: { type: "string", description: "Requested value where applicable." }, enabled: { type: "boolean", description: "Requested enabled state where applicable." }, content: { type: "string", description: "Proposed configuration where applicable." } }, required: [] },
];

const allSpecs: ToolSpec[] = [...specs, ...extendedLinuxSpecs];
const highRisk = new Set<ExtensionPermission>(allSpecs.filter(s => s.risk === "critical" || s.risk === "high").map(s => s.permission));

/** All distinct tools, one per Linux/Lennox capability. */
export const LINUX_PERMISSION_TOOLS: LinuxPermissionTool[] = allSpecs.map((spec) => {
  const name = spec.permission.replace(/-/g, "_");
  const risk = spec.risk ?? "high";
  return {
    name,
    permission: spec.permission,
    category: spec.category,
    description: spec.description,
    risk,
    inputSchema: {
      type: "object",
      properties: spec.properties ?? {},
      required: spec.required ?? [],
      additionalProperties: false,
    },
    execute: async (args, context, extensionId = "linux-permission-tools") => {
      if ((context.platform ?? process.platform) !== "linux") {
        throw new Error(`${name} is Linux-only; current platform is ${context.platform ?? process.platform}.`);
      }
      if (!context.isGranted(extensionId, spec.permission)) {
        throw new Error(`Permission denied: grant ${spec.permission} to ${extensionId} before calling ${name}.`);
      }
      if (risk === "high" || risk === "critical" || highRisk.has(spec.permission)) {
        const approved = await context.requestApproval({ tool: name, permission: spec.permission, args, risk });
        if (!approved) throw new Error(`Human approval denied for ${name}; no operation was performed.`);
      }
      const adapter = context.adapters[spec.permission];
      if (!adapter) {
        throw new Error(`Tool ${name} is registered, but no native adapter is configured for ${spec.permission}. No operation was performed.`);
      }
      return adapter(args);
    },
  };
});

/** Resolve a tool by its public name; useful to connect this catalogue to the agent's tool-call router. */
export function getLinuxPermissionTool(name: string): LinuxPermissionTool | undefined {
  return LINUX_PERMISSION_TOOLS.find(tool => tool.name === name);
}

/** Tool names and required permissions for UI discovery and permission screens. */
export function listLinuxPermissionTools(): Array<Pick<LinuxPermissionTool, "name" | "permission" | "category" | "description" | "risk" | "inputSchema">> {
  return LINUX_PERMISSION_TOOLS.map(({ execute: _execute, ...tool }) => tool);
}
