import type { PluginDefinition } from "./types.js";

export const PLUGIN_LIST: string[] = [
  "Location",
  "Camera",
  "Microphone",
  "Voice Activation",
  "Notifications",
  "Account Info",
  "Contacts",
  "Calendar",
  "Phone Calls",
  "Call History",
  "Email",
  "Tasks",
  "Messaging",
  "Radios",
  "Other Devices",
  "App Diagnostics",
  "File System",
  "Linux Permission Tools",
  "Screenshots",
  "Passkeys",
  "Browser",
  "Self Heal",
  "Plugin Maker",
  "Skill Maker",
  "Coding",
  "Image Generation",
  "Video Generation",
  "Game Development",
  "Multi Input",
  "Wiki",
];

export const LANGUAGE_SKILLS: string[] = [
  "ABAP", "ActionScript", "Ada", "Agda", "Alloy", "AMPL", "ANTLR", "ApacheConf", "Apex",
  "APL", "AppleScript", "Arc", "Arduino", "ASL", "ASN.1", "AspectJ", "Assembly", "ATS",
  "AutoHotkey", "AutoIt", "Awk", "Ballerina", "Batchfile", "Beef", "Befunge", "Berry",
  "Bicep", "Bison", "BitBake", "Blade", "BlitzMax", "Bluespec", "Boo", "Brainfuck",
  "Brightscript", "C", "C#", "C++", "C-ObjDump", "C2hs Haskell", "Cap'n Proto",
  "CartoCSS", "Ceylon", "Chapel", "Charity", "ChucK", "Cirru", "Clarion", "Clarity",
  "Clean", "Click", "Clojure", "Closure Templates", "CMake", "COBOL", "CodeQL",
  "CoffeeScript", "ColdFusion", "Common Lisp", "Component Pascal", "Cool", "Coq",
  "Crystal", "CSON", "CSS", "CSV", "Cuda", "CUE", "Curry", "CWeb", "Cycript", "Cython",
  "D", "Dafny", "Dart", "DataWeave", "Dhall", "DM", "Dockerfile", "DTrace", "Dylan",
  "E", "Earthly", "EBNF", "eC", "ECL", "EditorConfig", "Eiffel", "EJS", "Elixir",
  "Elm", "Emacs Lisp", "Erlang", "Euphoria", "F#", "F*", "Factor", "Fancy", "Fantom",
  "Faust", "Forth", "Fortran", "Futhark", "G-code", "Game Maker Language", "GAML",
  "GAP", "GDScript", "Gemini", "Genie", "Gherkin", "GLSL", "Gnuplot", "Go", "Golo",
  "Gosu", "Grace", "Gradle", "GraphQL", "Graphviz (DOT)", "Groovy", "GSC", "Hack",
  "Haml", "Handlebars", "Haskell", "Haxe", "HCL", "HLSL", "HolyC", "HTML", "HTTP",
  "Hy", "HyPhy", "Idris", "Ini", "Inno Setup", "Io", "Ioke", "Isabelle", "J",
  "Jasmine", "Java", "JavaScript", "Jinja", "Jison", "JSON", "Julia",
  "Jupyter Notebook", "Just", "Kaitai Struct", "Kotlin", "LabVIEW", "Lark", "Lasso",
  "Lean", "Less", "Lex", "LilyPond", "Liquid", "Literate Haskell",
  "LiveScript", "LLVM", "Logos", "Logtalk", "LOLCODE", "LSL", "Lua",
  "Makefile", "Mako", "Markdown", "Marko", "Mask", "Mathematica",
  "MATLAB", "Max", "MAXScript", "MDX", "Mercury", "Mermaid", "Meson", "Metal",
  "MiniD", "Mint", "Mirah", "MLIR",
  "Modelica", "Modula-2", "Modula-3", "Monkey", "Monkey C", "Moocode",
  "MoonScript", "Motoko", "Move", "MQL4", "MQL5", "MTML", "MUF", "Mustache",
  "Nasal", "NASL", "NCL", "Nearley", "Nemerle", "neon", "NetLinx",
  "NetLogo", "NewLisp", "Nextflow", "Nginx", "Nim", "Ninja", "Nit", "Nix",
  "NL", "NSIS", "Nu", "NumPy", "Nunjucks", "NWScript",
  "Objective-C", "Objective-C++", "Objective-J", "ObjectScript", "OCaml",
  "Odin", "Omgrofl", "ooc", "Opa", "Opal", "Open Policy Agent",
  "OpenCL", "OpenEdge ABL", "OpenSCAD", "Org", "Oxygene", "Oz",
  "P4", "Pan", "Papyrus", "Parrot", "Pascal", "Pawn", "PDDL",
  "Pep8", "Perl", "PHP", "Pic", "Pickle", "PicoLisp", "PigLatin",
  "Pike", "PLSQL", "Pony", "PostCSS", "PostScript", "PowerBuilder",
  "PowerShell", "Prisma", "Processing", "Prolog", "Promela",
  "Protocol Buffer", "Pug", "Puppet", "Pure Data", "PureBasic",
  "PureScript", "Pyret", "Python", "QML", "Qt Script", "Quake",
  "R", "Racket", "Ragel", "Raku", "RAML", "Rascal",
  "Reason", "Rebol", "Red", "Redcode", "Ren'Py",
  "ReScript", "reStructuredText", "REXX", "Ring",
  "RMarkdown", "RobotFramework", "Roff", "Rouge",
  "Ruby", "Rust", "Sage", "SaltStack", "SAS",
  "Sass", "Scala", "Scaml", "Scheme", "Scilab", "SCSS",
  "sed", "Self", "ShaderLab", "Shell", "Shen",
  "Sieve", "Singularity", "Slang", "Slice", "Slim", "Smali",
  "Smalltalk", "Smarty", "SMT", "Smithy", "SML",
  "Solidity", "Soong", "SourcePawn", "SPARQL", "SQF", "SQL",
  "Stan", "Standard ML", "Starlark", "Stata",
  "Stylus", "SugarSS", "SuperCollider", "Svelte", "SVG", "Sway",
  "Swift", "SWIG", "SystemVerilog", "Tcl", "Tcsh",
  "TeX", "Texinfo", "Text", "TOML", "TSX",
  "Turing", "Turtle", "Twig", "TypeScript",
  "Unified Parallel C", "Unix Assembly", "Uno", "UnrealScript",
  "Vala", "Valve Data Format", "VBA", "VBScript",
  "Velocity", "Verilog", "VHDL", "Vim Script",
  "Visual Basic .NET", "Visual Basic 6", "Vue", "Vyper",
  "WebAssembly", "WebIDL", "WGSL", "Wiki",
  "Workflow", "Wren", "X10", "xBase",
  "XML", "Xojo", "XQuery", "XSLT",
  "YACC", "YAML", "YANG", "YARA", "YASnippet",
  "ZAP", "Zeek", "ZenScript", "Zephir", "Zig", "Zil", "Zsh"
];

export const DEFAULT_PLUGIN_DEFINITIONS: Record<string, PluginDefinition> = {
  location: { id: "location", name: "Location", type: "api-connection", capabilities: ["location"] },
  camera: { id: "camera", name: "Camera", type: "api-connection", capabilities: ["camera"] },
  microphone: { id: "microphone", name: "Microphone", type: "api-connection", capabilities: ["microphone"] },
  notifications: { id: "notifications", name: "Notifications", type: "api-connection", capabilities: ["notifications"] },
  browser: { id: "browser", name: "Browser", type: "api-connection", capabilities: ["browser"] },
  "file-system": { id: "file-system", name: "File System", type: "api-connection", capabilities: ["file-system"] },
  "linux-permission-tools": { id: "linux-permission-tools", name: "Linux Permission Tools", type: "api-connection", capabilities: ["linux-permissions", "linux-file-read", "linux-file-write", "linux-chmod", "linux-acl-read", "linux-acl-write", "linux-service-control", "linux-selinux-context-read", "linux-apparmor-status-read", "lennox-admin-controls", "lennox-ordering", "lennox-inventory", "lennox-pricing-visibility", "lennox-warranty-returns", "linux-umask", "linux-default-acl", "linux-filesystem-quota", "linux-filesystem-project-id", "linux-filesystem-snapshot", "linux-filesystem-repair", "linux-filesystem-encryption", "linux-disk-encryption", "linux-logical-volume-management", "linux-software-raid", "linux-swap-management", "linux-filesystem-export", "linux-fuse-mounts", "linux-file-locks", "linux-filesystem-watchers", "linux-process-priority", "linux-process-scheduler", "linux-process-resource-limits", "linux-process-trace", "linux-cgroup-control", "linux-seccomp-policy", "linux-landlock-policy", "linux-bpf-control", "linux-perf-events", "linux-polkit-policy", "linux-pam-configuration", "linux-sudo-policy", "linux-login-session-control", "linux-user-session-control", "linux-authentication-status", "linux-account-lock-status", "linux-ssh-configuration", "linux-ssh-agent", "linux-gpg-keyring", "linux-keyring-management", "linux-trust-store", "linux-secure-boot-status", "linux-tpm-access", "linux-firmware-management", "linux-udev-rules", "linux-device-node-permissions", "linux-usb-access", "linux-serial-port-access", "linux-gpu-access", "linux-hardware-sensors", "linux-power-management", "linux-thermal-control", "linux-time-sync", "linux-locale-settings", "linux-dns-configuration", "linux-vpn-control", "linux-network-manager", "linux-packet-capture", "linux-traffic-control", "linux-proxy-settings", "linux-hosts-file", "linux-network-sharing", "linux-mdns-discovery", "linux-network-filesystems", "linux-dbus-policy", "linux-desktop-portals", "linux-notification-control", "linux-screen-lock-control", "linux-accessibility-control", "linux-speech-recognition", "linux-camera-device", "linux-scanner-access", "linux-print-queue-admin", "linux-flatpak-permissions", "linux-snap-permissions", "linux-app-permission-inventory", "linux-package-repository-admin", "linux-automatic-updates", "linux-kernel-log-access", "linux-journal-management", "linux-audit-policy", "linux-integrity-monitoring", "linux-yama-policy", "linux-smack-policy", "linux-tomoyo-policy", "linux-lsm-inventory", "linux-kernel-lockdown", "linux-module-signature-policy", "linux-iommu-status", "linux-virtualization-control", "linux-libvirt-control", "linux-systemd-unit-files", "linux-systemd-timers", "linux-user-crontab", "linux-service-permission-inventory", "linux-policykit-inventory", "linux-permission-inventory", "linux-permission-control-discovery", "linux-effective-access-check", "linux-file-execute", "linux-file-create-delete", "linux-file-metadata", "linux-chown", "linux-suid-sgid-sticky", "linux-extended-attributes", "linux-immutable-append-only", "linux-mount-unmount", "linux-removable-storage", "linux-user-group-read", "linux-user-group-admin", "linux-sudo-admin", "linux-process-inspect", "linux-process-control", "linux-package-management", "linux-kernel-modules", "linux-sysctl", "linux-hostname-time-power", "linux-boot-configuration", "linux-scheduled-jobs", "linux-environment-variables", "linux-system-logs", "linux-audit-logs", "linux-system-information", "linux-backup-restore", "linux-capabilities-admin", "linux-selinux-policy-admin", "linux-apparmor-policy-admin", "linux-security-policy-admin", "linux-firewall-admin", "linux-network-config", "linux-dbus-control", "linux-device-access", "linux-container-control", "linux-namespace-control", "linux-credential-store", "linux-ssh-key-access", "linux-certificate-store", "linux-cryptographic-key-access", "linux-screen-capture", "linux-audio-device", "linux-input-monitoring", "linux-keyboard-mouse-control", "linux-clipboard", "linux-display-settings", "linux-printer-access", "linux-bluetooth", "linux-wifi"] },
  coding: { id: "coding", name: "Coding Skill", type: "skill-expert", capabilities: ["coding"] },
};
