/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AppSelfImprovementRouteImport } from './routes/app/self-improvement'
import { Route as AppPlanningRouteImport } from './routes/app/planning'
import { Route as AppMemoryRouteImport } from './routes/app/memory'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppExperimentsRouteImport } from './routes/app/experiments'
import { Route as AppEvaluationRouteImport } from './routes/app/evaluation'
import { Route as AppChatHistoryRouteImport } from './routes/app/chat-history'
import { Route as AppChatGroupsRouteImport } from './routes/app/chat-groups'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppArchitectureRouteImport } from './routes/app/architecture'

const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppSelfImprovementRoute = AppSelfImprovementRouteImport.update({
  id: '/self-improvement',
  path: '/self-improvement',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationRoute = AppEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppChatHistoryRoute = AppChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => AppRoute,
} as any)
const AppChatGroupsRoute = AppChatGroupsRouteImport.update({
  id: '/chat-groups',
  path: '/chat-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/builder': typeof BuilderRoute
  '/desktop': typeof DesktopRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/chat': typeof AppChatRoute
  '/app/chat-groups': typeof AppChatGroupsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/self-improvement': typeof AppSelfImprovementRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/desktop': typeof DesktopRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/chat': typeof AppChatRoute
  '/app/chat-groups': typeof AppChatGroupsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/self-improvement': typeof AppSelfImprovementRoute
  '/app/store': typeof AppStoreRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/builder': typeof BuilderRoute
  '/desktop': typeof DesktopRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/chat': typeof AppChatRoute
  '/app/chat-groups': typeof AppChatGroupsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/experiments': typeof AppExperimentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/self-improvement': typeof AppSelfImprovementRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/builder'
    | '/desktop'
    | '/app/architecture'
    | '/app/chat'
    | '/app/chat-groups'
    | '/app/chat-history'
    | '/app/evaluation'
    | '/app/experiments'
    | '/app/knowledge'
    | '/app/memory'
    | '/app/planning'
    | '/app/self-improvement'
    | '/app/store'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/desktop'
    | '/app/architecture'
    | '/app/chat'
    | '/app/chat-groups'
    | '/app/chat-history'
    | '/app/evaluation'
    | '/app/experiments'
    | '/app/knowledge'
    | '/app/memory'
    | '/app/planning'
    | '/app/self-improvement'
    | '/app/store'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/builder'
    | '/desktop'
    | '/app/architecture'
    | '/app/chat'
    | '/app/chat-groups'
    | '/app/chat-history'
    | '/app/evaluation'
    | '/app/experiments'
    | '/app/knowledge'
    | '/app/memory'
    | '/app/planning'
    | '/app/self-improvement'
    | '/app/store'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  DesktopRoute: typeof DesktopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/self-improvement': {
      id: '/app/self-improvement'
      path: '/self-improvement'
      fullPath: '/app/self-improvement'
      preLoaderRoute: typeof AppSelfImprovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planning': {
      id: '/app/planning'
      path: '/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments': {
      id: '/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluation': {
      id: '/app/evaluation'
      path: '/evaluation'
      fullPath: '/app/evaluation'
      preLoaderRoute: typeof AppEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat-history': {
      id: '/app/chat-history'
      path: '/chat-history'
      fullPath: '/app/chat-history'
      preLoaderRoute: typeof AppChatHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat-groups': {
      id: '/app/chat-groups'
      path: '/chat-groups'
      fullPath: '/app/chat-groups'
      preLoaderRoute: typeof AppChatGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/architecture': {
      id: '/app/architecture'
      path: '/architecture'
      fullPath: '/app/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppChatRoute: typeof AppChatRoute
  AppChatGroupsRoute: typeof AppChatGroupsRoute
  AppChatHistoryRoute: typeof AppChatHistoryRoute
  AppEvaluationRoute: typeof AppEvaluationRoute
  AppExperimentsRoute: typeof AppExperimentsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppSelfImprovementRoute: typeof AppSelfImprovementRoute
  AppStoreRoute: typeof AppStoreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchitectureRoute: AppArchitectureRoute,
  AppChatRoute: AppChatRoute,
  AppChatGroupsRoute: AppChatGroupsRoute,
  AppChatHistoryRoute: AppChatHistoryRoute,
  AppEvaluationRoute: AppEvaluationRoute,
  AppExperimentsRoute: AppExperimentsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppSelfImprovementRoute: AppSelfImprovementRoute,
  AppStoreRoute: AppStoreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BuilderRoute: BuilderRoute,
  DesktopRoute: DesktopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
